name: Deploy to Vercel

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Vercel
      uses: vercel/action@v21.2.0
      with:
        args: 'deploy --prod'
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
